# Generated by Django 6.0.4 on 2026-08-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='prenom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='entreprise')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telephone')),
                ('subject', models.CharField(max_length=180, verbose_name='sujet')),
                ('message', models.TextField(verbose_name='message')),
                ('consent', models.BooleanField(verbose_name='consentement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('is_processed', models.BooleanField(default=False, verbose_name='traitee')),
            ],
            options={
                'verbose_name': 'demande de contact',
                'verbose_name_plural': 'demandes de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='prenom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('company', models.CharField(max_length=160, verbose_name='entreprise')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='fonction')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=40, verbose_name='telephone')),
                ('city', models.CharField(max_length=120, verbose_name='ville')),
                ('product_interest', models.CharField(max_length=180, verbose_name='materiel souhaite')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantite')),
                ('usage_description', models.TextField(verbose_name='usage prevu')),
                ('training_required', models.BooleanField(default=False, verbose_name='formation souhaitee')),
                ('additional_message', models.TextField(blank=True, verbose_name='message complementaire')),
                ('consent', models.BooleanField(verbose_name='consentement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('done', 'Traite'), ('archived', 'Archive')], default='new', max_length=20, verbose_name='statut')),
            ],
            options={
                'verbose_name': 'demande de devis materiel',
                'verbose_name_plural': 'demandes de devis materiel',
                'ordering': ['-created_at'],
            },
        ),
    ]
