# Generated by Django 6.0.4 on 2026-08-02 00:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='intitule')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('location', models.CharField(default='Rabat, Maroc', max_length=120, verbose_name='localisation')),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('autre', 'Autre')], default='stage', max_length=20, verbose_name='type de contrat')),
                ('short_description', models.TextField(max_length=500, verbose_name='resume court')),
                ('description', models.TextField(verbose_name='description')),
                ('profile', models.TextField(blank=True, verbose_name='profil recherche')),
                ('requirements', models.TextField(blank=True, verbose_name='prerequis')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de publication')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='date limite')),
                ('is_active', models.BooleanField(default=False, verbose_name='visible publiquement')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
            ],
            options={
                'verbose_name': "offre d'emploi",
                'verbose_name_plural': "offres d'emploi",
                'ordering': ['display_order', '-published_at', 'title'],
            },
        ),
    ]
