# Generated by Django 6.0.7 on 2026-08-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='missions',
            field=models.TextField(blank=True, verbose_name='missions'),
        ),
    ]
