# Generated by Django 6.0.7 on 2026-08-15 00:40

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nom')),
                ('logo', models.ImageField(blank=True, upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg']), core.models.validate_image_size], verbose_name='logo')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=False, verbose_name='actif')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
            ],
            options={
                'verbose_name': 'partenaire',
                'verbose_name_plural': 'partenaires',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('client', models.CharField(blank=True, max_length=160, verbose_name='client')),
                ('location', models.CharField(blank=True, max_length=140, verbose_name='localisation')),
                ('mission_type', models.CharField(blank=True, max_length=140, verbose_name='type de mission')),
                ('short_description', models.TextField(max_length=500, verbose_name='resume court')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size], verbose_name='image')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='date de realisation')),
                ('is_published', models.BooleanField(default=False, verbose_name='publie')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
            ],
            options={
                'verbose_name': 'realisation',
                'verbose_name_plural': 'realisations',
                'ordering': ['display_order', '-completion_date', 'title'],
            },
        ),
    ]
