# Generated by Django 6.0.7 on 2026-08-15 00:40

import catalog.models
import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
            ],
            options={
                'verbose_name': 'categorie produit',
                'verbose_name_plural': 'categories produits',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nom')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('brand', models.CharField(blank=True, max_length=140, verbose_name='marque')),
                ('short_description', models.TextField(max_length=500, verbose_name='resume court')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size], verbose_name='image')),
                ('technical_document', models.FileField(blank=True, upload_to='products/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), catalog.models.validate_document_size], verbose_name='document technique')),
                ('is_active', models.BooleanField(default=False, verbose_name='actif')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifie le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory', verbose_name='categorie')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
